GET http://localhost:1337/api/Home
Authorization: 

###

GET http://localhost:1337/api/game-categories
Authorization: 

###

GET http://localhost:1337/api/games
Authorization: 

###
//Para filtrar los juegos por categorias

GET http://localhost:1337/api/games?filters[game_category][name][$contains]=Action
Authorization:


###

//En caso de que haya imagenes que no se les pase como url sino como archivo a strapi

GET http://localhost:1337/api/home?populate=cover
Authorization:

###

GET http://localhost:1337/api/game-categories?populate=image
Authorization: 
###

//En caso de querer solo un campo para optimizar el rendimiento de la api

//Devolvería solo el name
GET http://localhost:1337/api/game-categories?
fields=name
Authorization: 

###

//Devolvería los campos que necesitemos
GET http://localhost:1337/api/games?fields[0]=slug&fields[1]=description&populate[image][fields][0]=url
Authorization:
